### ISSUE TITLE
chain: TODO for v1.6.0

### ISSUE THREAD

**Issue by VandeurenGlenn** [leofcoin/monorepo#61]
# TODO

- [ ] ~~all native contracts are proxied (less hasle when upgrading a contract~~
- [ ] ~~proxy manager standard~~
- [x] add stateStore (contracts can be loaded using the state) (introduces breaking change, devs need to make the state of their contract exposable ) see #82 
- [x] add snapshotting (recover from state/decide from where to recover)
- [x] validators produce blocks
- [x] syncs blocks with other nodes
- [x] double contracts throw and are not added (no cost)
- [x] transactions that fail are ignored (no cost and less resource usage)
- [x] native contracts that are internally used by the chain (iow no need for a wrapped token)
- [x] can add/remove validators
- [x] add roles standard
- [ ] add TS parser to generate ABI
- [ ] add contract builder
- [ ] contracts can be upgraded and inited using state (be carefull! once the storage is set to the new contract it's no longer available in the old contract)
- [ ] native voting system
- [ ] contracts should be able to use already published libs/helpers
- [ ] a libcontract should be made so we can track libs etc by their version & have a decent place where devs can fetch a list of available ones & ability to deploy/ask to deploy new libs (they cost lot of effort, a lib can only be removed once every contract updated to another lib or newer version)
- [ ] libs/helpers should be avaiable using the LibContract

## edits
- 17/11/2022 - remove proxies & proxy manager, when stateStore is implemented, proxies are not needed.
- 25/09/2024 - update todo: add LibContract & contract-tools
